### ISSUE TITLE
error: precondition required

### ISSUE THREAD

**Issue by pxawtyy** [AYUSH-PANDEY023/Maria-MD#147]
i used the bot normally a week ago, however, out of nowhere, i went to reconnect and came across this error that hasn't gone away since. i did make some changes to the code, but there was nothing wrong with what i changed (i think, because it was working fine), it happened suddenly. i use termux.

/storage/emulated/0/Download/.Maria-MD-main/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed
    at sendRawMessage (/storage/emulated/0/Download/.Maria-MD-main/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:19)
    at sendNode (/storage/emulated/0/Download/.Maria-MD-main/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:73:16)
    at Object.requestPairingCode (/storage/emulated/0/Download/.Maria-MD-main/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
    at async Timeout._onTimeout (/storage/emulated/0/Download/.Maria-MD-main/plugins.js:89:21) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

idk if this error is because of whiskeysockets or something else, because i changed the version (of whiskeysockets) and it didn't worked too.

anyways, "plugins.js:89:21":

88 setTimeout(async () => {
89          let code = await Maria.requestPairingCode(phoneNumber)
90          code = code?.match(/.{1,4}/g)?.join("-") || code
91          console.log(chalk.black(chalk.bgGreen(`🤖 seu código: `)), chalk.black(chalk.white(code)))
92       }, 3000)
93    }

**Comment by AYUSH-PANDEY023** [comment]
Reforked the repository for updates and improvements.
